arch = { packages = [
  "1password",
  "1password-cli",
  "accountsservice",
  "adobe-source-han-sans-cn-fonts",
  "adobe-source-han-sans-jp-fonts",
  "adobe-source-han-sans-kr-fonts",
  "adw-gtk-theme",
  "alsa-firmware",
  "alsa-plugins",
  "alsa-utils",
  "apr",
  "apr-util",
  "arch-install-scripts",
  "asciinema",
  "asciinema-agg",
  "awesome-terminal-fonts",
  "base",
  "base-devel",
  "bash-completion",
  "bat",
  "bats",
  "bats-assert",
  "bats-file",
  "bc",
  "bind",
  "blesh-git",
  "blueman",
  "bluez",
  "bluez-hid2hci",
  "bluez-libs",
  "bluez-utils",
  "breeze",
  "breezy",
  "brightnessctl",
  "btop",
  "btrfs-assistant",
  "btrfs-progs",
  "bully",
  "chezmoi",
  "chwd",
  "cliphist",
  "cmatrix-git",
  "cowpatty",
  "cpio",
  "cpupower",
  "cryptsetup",
  "cuda",
  "cudnn",
  "cython",
  "dasel",
  "ddcutil",
  "device-mapper",
  "devtools",
  "dhclient",
  "diffutils",
  "discord",
  "dmidecode",
  "dmraid",
  "dnsmasq",
  "docker",
  "docker-compose",
  "dolphin",
  "dos2unix",
  "dosfstools",
  "duf",
  "e2fsprogs",
  "efibootmgr",
  "efitools",
  "egl-wayland",
  "ethtool",
  "ex-vi-compat",
  "exfatprogs",
  "expac",
  "f2fs-tools",
  "fastfetch",
  "ffmpegthumbnailer",
  "firefox",
  "fsarchiver",
  "gd",
  "ghostscript",
  "ghostty",
  "git",
  "github-cli",
  "glances",
  "glow",
  "gnome-keyring",
  "go",
  "gpu-screen-recorder-ui",
  "graphviz",
  "greetd",
  "grim",
  "grimblast-git",
  "gsfonts",
  "gst-libav",
  "gst-plugin-pipewire",
  "gst-plugins-bad",
  "gst-plugins-ugly",
  "gtk-engine-murrine",
  "gts",
  "gum",
  "haveged",
  "hcxdumptool",
  "hcxtools",
  "hdf5",
  "hdparm",
  "heroic-games-launcher-bin",
  "hwdetect",
  "hwinfo",
  "hypridle",
  "hyprland",
  "hyprlauncher",
  "hyprlock",
  "hyprpaper",
  "hyprpicker",
  "hyprpolkitagent",
  "hyprsunset",
  "inetutils",
  "intel-media-driver",
  "intel-oneapi-common",
  "intel-oneapi-compiler-shared-runtime-libs",
  "intel-oneapi-openmp",
  "intel-oneapi-tcm",
  "intel-ucode",
  "iptables-nft",
  "iwd",
  "jc",
  "jfsutils",
  "john",
  "kanata",
  "kitty",
  "kservice",
  "kvantum",
  "less",
  "level-zero-loader",
  "lib32-libva-intel-driver",
  "lib32-mesa",
  "lib32-nvidia-utils",
  "lib32-opencl-nvidia",
  "lib32-vulkan-intel",
  "libaec",
  "libdvdcss",
  "libgsf",
  "libheif",
  "liblzf",
  "libopenraw",
  "libqalculate",
  "libva-intel-driver",
  "libva-nvidia-driver",
  "libwnck3",
  "libxpm",
  "limine",
  "limine-mkinitcpio-hook",
  "limine-snapper-sync",
  "linux-firmware",
  "logrotate",
  "lsb-release",
  "lshw",
  "lsscsi",
  "lvm2",
  "macchanger",
  "man-db",
  "man-pages",
  "matugen",
  "maturin",
  "mdadm",
  "meld",
  "mercurial",
  "mesa-utils",
  "metapac",
  "micro",
  "mkinitcpio",
  "modemmanager",
  "mtools",
  "nccl",
  "neovim",
  "nerd-fonts-inter",
  "net-tools",
  "netctl",
  "netpbm",
  "networkmanager",
  "networkmanager-openvpn",
  "nfs-utils",
  "nilfs-utils",
  "nmap",
  "noto-color-emoji-fontconfig",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "noto-fonts-extra",
  "nss-mdns",
  "ntfs-3g",
  "ntp",
  "nvidia-prime",
  "nvidia-settings",
  "nvidia-utils",
  "nvm",
  "obsidian",
  "octopi",
  "onednn",
  "onnxruntime-cuda",
  "opencl-nvidia",
  "opencode-bin",
  "opendesktop-fonts",
  "openssh",
  "os-prober",
  "pacman-contrib",
  "paru",
  "pavucontrol",
  "perl",
  "pipewire-alsa",
  "pipewire-pulse",
  "playerctl",
  "plocate",
  "plymouth",
  "pngcheck",
  "poppler-glib",
  "power-profiles-daemon",
  "protonplus",
  "protonup-qt",
  "protonutils",
  "pv",
  "pybind11",
  "python",
  "python-absl",
  "python-anyio",
  "python-asgiref",
  "python-astor",
  "python-astunparse",
  "python-attrs",
  "python-audioop-lts",
  "python-bcrypt",
  "python-binaryornot",
  "python-bleach",
  "python-boolean.py",
  "python-boto3",
  "python-botocore",
  "python-capstone",
  "python-coloredlogs",
  "python-configobj",
  "python-debian",
  "python-defusedxml",
  "python-dotenv",
  "python-dulwich",
  "python-et-xmlfile",
  "python-fastbencode",
  "python-flatbuffers",
  "python-fluidity",
  "python-gast",
  "python-gmpy2",
  "python-google-auth",
  "python-google-auth-oauthlib",
  "python-grpcio",
  "python-grpcio-tools",
  "python-h11",
  "python-h5py",
  "python-hatch",
  "python-httpcore",
  "python-httplib2",
  "python-httptools",
  "python-httpx",
  "python-humanfriendly",
  "python-hyperlink",
  "python-iniconfig",
  "python-invoke",
  "python-jinja",
  "python-jmespath",
  "python-keras",
  "python-lexicon",
  "python-license-expression",
  "python-markdownify",
  "python-markupsafe",
  "python-maturin",
  "python-merge3",
  "python-ml-dtypes",
  "python-mpmath",
  "python-oauth2client",
  "python-oauthlib",
  "python-olefile",
  "python-onnxruntime-cuda",
  "python-openpyxl",
  "python-opt_einsum",
  "python-optree",
  "python-packaging",
  "python-paramiko",
  "python-pasta",
  "python-pathvalidate",
  "python-patiencediff",
  "python-pdfminer",
  "python-pipx",
  "python-pooch",
  "python-protobuf",
  "python-puremagic",
  "python-py-cpuinfo",
  "python-pyasn1",
  "python-pyasn1-modules",
  "python-pydot",
  "python-pydub",
  "python-pyelftools",
  "python-pyflakes",
  "python-pynacl",
  "python-pytest",
  "python-requests-oauthlib",
  "python-respx",
  "python-rsa",
  "python-s3transfer",
  "python-scikit-build-core",
  "python-scipy",
  "python-spur",
  "python-standard-aifc",
  "python-standard-cgi",
  "python-standard-chunk",
  "python-starlette",
  "python-sympy",
  "python-tensorboard_plugin_wit",
  "python-tensorflow",
  "python-terminaltexteffects",
  "python-tomli-w",
  "python-tomlkit",
  "python-uv",
  "python-uvloop",
  "python-websockets",
  "python-werkzeug",
  "python-wrapt",
  "python-xlsxwriter",
  "qq-git",
  "qt6-languageserver",
  "qt6ct-kde",
  "quickshell",
  "reaver",
  "rebuild-detector",
  "reflector",
  "reuse",
  "rink",
  "ripgrep",
  "rofi",
  "rsync",
  "rtkit",
  "s-nail",
  "satty",
  "sbctl",
  "scdoc",
  "scopebuddy-git",
  "serf",
  "sg3_utils",
  "slurp",
  "smartmontools",
  "snapper",
  "sof-firmware",
  "starship",
  "strace",
  "subversion",
  "sudo",
  "switcheroo-control",
  "sysfsutils",
  "telegram-desktop",
  "tensorboard",
  "texinfo",
  "tldr",
  "tmux",
  "tokyonight-gtk-theme-git",
  "tree",
  "ttf-bitstream-vera",
  "ttf-dejavu",
  "ttf-fantasque-nerd",
  "ttf-hack",
  "ttf-jetbrains-mono-nerd",
  "ttf-lato",
  "ttf-liberation",
  "ttf-material-symbols-variable-git",
  "ttf-meslo-nerd",
  "ttf-opensans",
  "ufw",
  "ufw-docker",
  "unixodbc",
  "unrar",
  "unzip",
  "upower",
  "usb_modeswitch",
  "usbutils",
  "uv",
  "uvicorn",
  "vim",
  "vlc",
  "vulkan-intel",
  "wallust",
  "waydroid",
  "waydroid-script-git",
  "wget",
  "which",
  "wifite",
  "winboat",
  "wireless-regdb",
  "wireplumber",
  "wireshark-cli",
  "wl-clipboard",
  "wpa_supplicant",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-hyprland",
  "xdg-user-dirs",
  "xf86-input-libinput",
  "xfsprogs",
  "xl2tpd",
  "xorg-server",
  "xorg-xdpyinfo",
  "xorg-xinit",
  "xorg-xinput",
  "xorg-xkill",
  "xorg-xrandr",
  "zathura",
  "zathura-pdf-mupdf",
  "zen-browser-bin",
] }

npm = { packages = [
    "corepack",
    "npm",
    "prettier",
    "prettier-plugin-awk",
] }

pipx = { packages = [
    "markitdown",
    "vdf2json",
] }
