arch = { packages = [
  "accountsservice",
  "alacritty",
  "alsa-firmware",
  "alsa-plugins",
  "alsa-utils",
  "awesome-terminal-fonts",
  "base",
  "base-devel",
  "bash-completion",
  "bind",
  "bluez",
  "bluez-hid2hci",
  "bluez-libs",
  "bluez-obex",
  "bluez-utils",
  "btop",
  "btrfs-assistant",
  "btrfs-progs",
  "cachyos-fish-config",
  "cachyos-gaming-applications",
  "cachyos-gaming-meta",
  "cachyos-grub-theme",
  "cachyos-hello",
  "cachyos-hooks",
  "cachyos-kernel-manager",
  "cachyos-keyring",
  "cachyos-micro-settings",
  "cachyos-mirrorlist",
  "cachyos-packageinstaller",
  "cachyos-plymouth-bootanimation",
  "cachyos-plymouth-theme",
  "cachyos-rate-mirrors",
  "cachyos-settings",
  "cachyos-snapper-support",
  "cachyos-v3-mirrorlist",
  "cachyos-v4-mirrorlist",
  "cachyos-wallpapers",
  "cachyos-zsh-config",
  "cantarell-fonts",
  "chwd",
  "cpupower",
  "cryptsetup",
  "device-mapper",
  "diffutils",
  "dmidecode",
  "dmraid",
  "dnsmasq",
  "dosfstools",
  "duf",
  "e2fsprogs",
  "efibootmgr",
  "efitools",
  "ethtool",
  "exfatprogs",
  "f2fs-tools",
  "fastfetch",
  "ffmpegthumbnailer",
  "firefox",
  "fsarchiver",
  "git",
  "glances",
  "growpartfs",
  "gst-libav",
  "gst-plugin-pipewire",
  "gst-plugins-bad",
  "gst-plugins-ugly",
  "gtkmm3",
  "hdparm",
  "hwdetect",
  "hwinfo",
  "inetutils",
  "intel-ucode",
  "iptables",
  "iwd",
  "jfsutils",
  "less",
  "libdvdcss",
  "libgsf",
  "libopenraw",
  "limine",
  "limine-mkinitcpio-hook",
  "limine-snapper-sync",
  "linux-cachyos",
  "linux-cachyos-headers",
  "linux-cachyos-lts",
  "linux-cachyos-lts-headers",
  "linux-cachyos-nvidia-open",
  "linux-firmware",
  "logrotate",
  "lsb-release",
  "lsscsi",
  "lvm2",
  "man-db",
  "man-pages",
  "mdadm",
  "meld",
  "mesa-utils",
  "micro",
  "mkinitcpio",
  "modemmanager",
  "mtools",
  "netctl",
  "networkmanager",
  "networkmanager-openvpn",
  "nfs-utils",
  "nilfs-utils",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "nss-mdns",
  "open-vm-tools",
  "openssh",
  "os-prober",
  "pacman-contrib",
  "paru",
  "pavucontrol",
  "perl",
  "pipewire-alsa",
  "pipewire-pulse",
  "pkgfile",
  "plocate",
  "plymouth",
  "poppler-glib",
  "power-profiles-daemon",
  "pv",
  "python",
  "python-defusedxml",
  "python-packaging",
  "qemu-guest-agent",
  "rebuild-detector",
  "reflector",
  "ripgrep",
  "rsync",
  "s-nail",
  "sg3_utils",
  "shelly",
  "smartmontools",
  "snapper",
  "sof-firmware",
  "spice-vdagent",
  "sudo",
  "sysfsutils",
  "texinfo",
  "ttf-bitstream-vera",
  "ttf-dejavu",
  "ttf-liberation",
  "ttf-meslo-nerd",
  "ttf-opensans",
  "ufw",
  "ufw-extras",
  "unrar",
  "unzip",
  "upower",
  "usb_modeswitch",
  "usbutils",
  "vim",
  "virtualbox-guest-utils",
  "vlc-plugins-all",
  "vulkan-virtio",
  "wget",
  "which",
  "wireplumber",
  "wpa_supplicant",
  "xdg-user-dirs",
  "xf86-input-vmmouse",
  "xfsprogs",
  "xl2tpd",

  # Gaming (Steam/Lutris/Wine)
  "7zip",
  "gamescope",
  "goverlay",
  "lib32-acl",
  "lib32-alsa-lib",
  "lib32-alsa-plugins",
  "lib32-at-spi2-core",
  "lib32-attr",
  "lib32-cairo",
  "lib32-colord",
  "lib32-dbus",
  "lib32-fontconfig",
  "lib32-freetype2",
  "lib32-fribidi",
  "lib32-gdk-pixbuf2",
  "lib32-gettext",
  "lib32-giflib",
  "lib32-glew",
  "lib32-glib2",
  "lib32-glu",
  "lib32-gtk3",
  "lib32-harfbuzz",
  "lib32-lcms2",
  "lib32-libcups",
  "lib32-libdatrie",
  "lib32-libepoxy",
  "lib32-libice",
  "lib32-libjpeg-turbo",
  "lib32-libnl",
  "lib32-libnm",
  "lib32-libpcap",
  "lib32-libpipewire",
  "lib32-libpng",
  "lib32-librsvg",
  "lib32-libsm",
  "lib32-libthai",
  "lib32-libtiff",
  "lib32-libunwind",
  "lib32-libva",
  "lib32-libxcomposite",
  "lib32-libxcrypt-compat",
  "lib32-libxcursor",
  "lib32-libxdamage",
  "lib32-libxfixes",
  "lib32-libxft",
  "lib32-libxi",
  "lib32-libxinerama",
  "lib32-libxkbcommon",
  "lib32-libxmu",
  "lib32-libxrandr",
  "lib32-libxrender",
  "lib32-libxss",
  "lib32-libxt",
  "lib32-libxtst",
  "lib32-mangohud",
  "lib32-mpg123",
  "lib32-nspr",
  "lib32-nss",
  "lib32-ocl-icd",
  "lib32-openal",
  "lib32-pango",
  "lib32-pcre2",
  "lib32-pipewire",
  "lib32-pixman",
  "lib32-sqlite",
  "lib32-util-linux",
  "lib32-vulkan-icd-loader",
  "libxcrypt-compat",
  "lsof",
  "lutris",
  "mangohud",
  "proton-cachyos-slr",
  "protontricks",
  "steam",
  "steam-devices",
  "umu-launcher",
  "vulkan-icd-loader",
  "vulkan-tools",
  "webkit2gtk-4.1",
  "wine",
  "wine-cachyos-opt",
  "winetricks",
  "zenity",
] }
