arch = [
  "1password",
  "1password-cli",
  "accountsservice",
  "adobe-source-han-sans-cn-fonts",
  "adobe-source-han-sans-jp-fonts",
  "adobe-source-han-sans-kr-fonts",
  "adw-gtk-theme",
  "alsa-firmware",
  "alsa-plugins",
  "alsa-utils",
  "awesome-terminal-fonts",
  "base",
  "base-devel",
  "bash-completion",
  "bat",
  "bats",
  "bats-assert",
  "bats-file",
  "bind",
  "blesh-git",
  "bluez",
  "bluez-hid2hci",
  "bluez-libs",
  "bluez-utils",
  "breeze",
  "brightnessctl",
  "btop",
  "btrfs-assistant",
  "btrfs-progs",
  "bully",
  "chezmoi",
  "chwd",
  "cmatrix-git",
  "cowpatty",
  "cpio",
  "cpupower",
  "cryptsetup",
  "dasel",
  "ddcutil",
  "device-mapper",
  "dhclient",
  "diffutils",
  "discord",
  "dmidecode",
  "dmraid",
  "dnsmasq",
  "dolphin",
  "dos2unix",
  "dosfstools",
  "duf",
  "e2fsprogs",
  "efibootmgr",
  "efitools",
  "egl-wayland",
  "elephant",
  "elephant-calc",
  "elephant-clipboard",
  "elephant-desktopapplications",
  "elephant-symbols",
  "elephant-unicode",
  "ethtool",
  "exfatprogs",
  "f2fs-tools",
  "fastfetch",
  "ffmpegthumbnailer",
  "firefox",
  "fsarchiver",
  "ghostty",
  "git",
  "github-cli",
  "glances",
  "gnome-keyring",
  "go",
  "greetd",
  "grim",
  "grimblast-git",
  "grub",
  "grub-btrfs-support",
  "grub-hook",
  "gst-libav",
  "gst-plugin-pipewire",
  "gst-plugins-bad",
  "gst-plugins-ugly",
  "gtk-engine-murrine",
  "harsh",
  "haveged",
  "hcxdumptool",
  "hcxtools",
  "hdparm",
  "heroic-games-launcher-bin",
  "hwdetect",
  "hwinfo",
  "hypridle",
  "hyprland",
  "hyprlock",
  "hyprpaper",
  "hyprpicker",
  "hyprpolkitagent",
  "hyprsunset",
  "inetutils",
  "intel-media-driver",
  "intel-ucode",
  "iptables-nft",
  "iwd",
  "jc",
  "jfsutils",
  "john",
  "kanata",
  "kitty",
  "kservice",
  "kvantum",
  "less",
  "lib32-libva-intel-driver",
  "lib32-mesa",
  "lib32-nvidia-utils",
  "lib32-opencl-nvidia",
  "lib32-vulkan-intel",
  "libdvdcss",
  "libgsf",
  "libopenraw",
  "libqalculate",
  "libva-intel-driver",
  "libva-nvidia-driver",
  "libwnck3",
  "linux-cachyos",
  "linux-firmware",
  "logrotate",
  "lsb-release",
  "lshw",
  "lsscsi",
  "lvm2",
  "macchanger",
  "man-db",
  "man-pages",
  "matugen-bin",
  "mdadm",
  "meld",
  "mesa-utils",
  "metapac",
  "micro",
  "mkinitcpio",
  "modemmanager",
  "mtools",
  "neovim",
  "nerd-fonts-inter",
  "netctl",
  "net-tools",
  "networkmanager",
  "networkmanager-openvpn",
  "nfs-utils",
  "nilfs-utils",
  "noto-color-emoji-fontconfig",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "noto-fonts-extra",
  "nss-mdns",
  "ntfs-3g",
  "ntp",
  "nvidia-dkms",
  "nvidia-prime",
  "nvidia-settings",
  "nvidia-utils",
  "nvm",
  "obsidian",
  "octopi",
  "opencl-nvidia",
  "opencode-bin",
  "opendesktop-fonts",
  "openssh",
  "os-prober",
  "pacman-contrib",
  "paru",
  "pavucontrol",
  "perl",
  "pipewire-alsa",
  "pipewire-pulse",
  "playerctl",
  "plocate",
  "plymouth",
  "pngcheck",
  "poppler-glib",
  "power-profiles-daemon",
  "protonplus",
  "protonup-qt",
  "protonutils",
  "pv",
  "python",
  "python-capstone",
  "python-defusedxml",
  "python-packaging",
  "python-pipx",
  "python-pyelftools",
  "qt6ct-kde",
  "quickshell",
  "reaver",
  "rebuild-detector",
  "reflector",
  "rink",
  "ripgrep",
  "rofi",
  "rsync",
  "rtkit",
  "satty",
  "sbctl",
  "scdoc",
  "sg3_utils",
  "slurp",
  "smartmontools",
  "s-nail",
  "snapper",
  "sof-firmware",
  "spotify",
  "starship",
  "strace",
  "sudo",
  "switcheroo-control",
  "sysfsutils",
  "texinfo",
  "tldr",
  "tmux",
  "tokyonight-gtk-theme-git",
  "tree",
  "ttf-bitstream-vera",
  "ttf-dejavu",
  "ttf-fantasque-nerd",
  "ttf-hack",
  "ttf-jetbrains-mono-nerd",
  "ttf-lato",
  "ttf-liberation",
  "ttf-material-symbols-variable-git",
  "ttf-meslo-nerd",
  "ttf-opensans",
  "ufw",
  "ufw-docker",
  "unrar",
  "unzip",
  "upower",
  "usb_modeswitch",
  "usbutils",
  "vi",
  "vim",
  "vlc",
  "vulkan-intel",
  "walker",
  "wallust",
  "wget",
  "which",
  "wifite",
  "wireless-regdb",
  "wireplumber",
  "wireshark-cli",
  "wl-clipboard",
  "wpa_supplicant",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-hyprland",
  "xdg-user-dirs",
  "xf86-input-libinput",
  "xfsprogs",
  "xl2tpd",
  "xorg-server",
  "xorg-xdpyinfo",
  "xorg-xinit",
  "xorg-xinput",
  "xorg-xkill",
  "xorg-xrandr",
  "zathura",
  "zathura-pdf-mupdf",
  "zen-browser-bin",
]
pipx = ["vdf2json"]
