arch = [
  "apr",
  "apr-util",
  "arch-install-scripts",
  "breezy",
  "devtools",
  "expac",
  "glow",
  "gum",
  "mercurial",
  "python-attrs",
  "python-binaryornot",
  "python-boolean.py",
  "python-configobj",
  "python-debian",
  "python-dulwich",
  "python-fastbencode",
  "python-jinja",
  "python-license-expression",
  "python-markupsafe",
  "python-merge3",
  "python-patiencediff",
  "python-tomlkit",
  "reuse",
  "serf",
  "subversion",
]
