arch = [
  "cachyos-gaming-applications",
  "cachyos-gaming-meta",
  "cachyos-grub-theme",
  "cachyos-hello",
  "cachyos-hooks",
  "cachyos-kernel-manager",
  "cachyos-keyring",
  "cachyos-micro-settings",
  "cachyos-mirrorlist",
  "cachyos-packageinstaller",
  "cachyos-plymouth-bootanimation",
  "cachyos-plymouth-theme",
  "cachyos-rate-mirrors",
  "cachyos-settings",
  "cachyos-v3-mirrorlist",
  "cachyos-v4-mirrorlist",
  "cachyos-wallpapers",
  "cachyos-zsh-config",
  "linux-cachyos-headers",
]
