[cask]
  1password = "8.12.8"
  1password-cli = "2.33.1"
  adobe-acrobat-reader = "25.001.21288"
  alacritty = "0.16.1"
  android-platform-tools = "37.0.0"
  font-inter = "4.1"
  font-jetbrains-mono-nerd-font = "3.4.0"
  ghostty = "1.3.1"
  google-chrome = "146.0.7680.165"
  hiddenbar = "1.10"
  localsend = "1.17.0"
  microsoft-teams = "26059.604.4471.2584"
  mouseless = "0.4.3"
  obsidian = "1.12.7"
  ovim = "latest"
  raycast = "1.104.11"
  slack = "4.48.102"
  wireshark-app = "4.6.4"
  zen = "1.19.5b"

