[cask]
  1password = "8.12.5"
  1password-cli = "2.32.1"
  adobe-acrobat-reader = "25.001.21223"
  alacritty = "0.16.1"
  android-platform-tools = "36.0.2"
  font-inter = "4.1"
  font-jetbrains-mono-nerd-font = "3.4.0"
  ghostty = "1.2.3"
  google-chrome = "145.0.7632.160"
  hiddenbar = "1.10"
  localsend = "1.17.0"
  microsoft-teams = "25290.302.4044.3989"
  mouseless = "0.4.3"
  obsidian = "1.12.4"
  ovim = "latest"
  raycast = "1.104.8"
  slack = "4.48.99"
  wireshark-app = "4.6.4"
  zen = "1.19.1b"

