#!/usr/bin/env bash

exit-screensaver() {
    pkill -x cmatrix 2>/dev/null
    pkill -f 'kitty --start-as fullscreen --class Screensaver screensaver-cmd'
    exit 0
}

trap exit-screensaver SIGINT SIGTERM SIGHUP SIGQUIT

sleep 0.5
exec cmatrix -s
