##! Execute
bindd = SUPER CTRL ALT, T, Ghostty, exec, launch-or-focus com.mitchellh.ghostty
bindd = SUPER, G, Steam, exec, launch-or-focus steam
bindd = SUPER CTRL ALT, Z, Zen Browser, exec, launch-or-focus zen
bindd = SUPER CTRL ALT, D, Discord, exec, launch-or-focus discord

##! Workspace
bind = SUPER, Z, togglespecialworkspace, first
bind = SUPER SHIFT, Z, movetoworkspacesilent, special:first

##! Other
bindd = CTRL ALT, Space, Switch keyboard layout, exec, switch-layout
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, dms ipc notifications clearAll
bindd = SUPER SHIFT, A, Switch audio output, exec, dms ipc audio cycleoutput
