exec-once = echo -n '' | gnome-keyring-daemon --replace --unlock --components=secrets
exec-once = systemctl --user start hyprland-session.target
exec-once = limine-snapper-restore --notify
exec-once = sleep 5 && QS_NO_RELOAD_POPUP=1 QML_DISABLE_DISK_CACHE=1 quickshell --no-duplicate
