format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""
palette = "black_metal_venom"

[palettes.black_metal_venom]
accent = "#5f8787"
danger = "#79241f"
muted = "#888888"
subtle = "#999999"
text = "#c1c1c1"
bright = "#f8f7f2"

[directory]
truncation_length = 2
style = "text"

[character]
success_symbol = "[❯](accent)"
error_symbol = "[❯](bold danger)"
vimcmd_symbol = "[❮](bright)"

[git_branch]
format = "[$branch]($style)"
style = "muted"

[git_status]
format = "($conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind)"
style = "accent"
conflicted = "[~${count}](bold danger) "
staged = "[+${count}](bold danger) "
modified = "[!${count}](bold danger) "
renamed = "[»${count}](bold danger) "
deleted = "[✘${count}](bold danger) "
untracked = "[?${count}](accent) "
stashed = "[*${count}](accent) "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "muted"

[cmd_duration]
format = "[$duration]($style) "
style = "subtle"

[python]
format = "[$virtualenv]($style) "
style = "muted"
