[cask]
  1password = "8.11.12"
  1password-cli = "2.32.0"
  adobe-acrobat-reader = "25.001.20756"
  discord = "0.0.363"
  font-inter = "4.1"
  font-jetbrains-mono-nerd-font = "3.4.0"
  ghostty = "1.2.2"
  google-chrome = "141.0.7390.77"
  mouseless = "0.4.2"
  obsidian = "1.9.14"
  raycast = "1.103.3"
  rustdesk = "1.4.2"
  slack = "4.46.101"
  spotify = "1.2.74.477"
  whatsapp = "2.25.28.75"
  zen = "1.16.4b"
  zoom = "6.6.2.65462"

