[packages]
common = [
	"alacritty",
	"asciinema",
	"bat",
	"blesh-git",
	"fastfetch",
	"firefox",
	"fzf",
	"git",
	"github-cli",
	"go",
	"gomatrix-git",
	"keychain",
	"lftp",
	"neovim",
	"nvm",
	"ripgrep",
	"rsync",
	"tmux",
	"tree",
	"ttf-jetbrains-mono-nerd",
	"vim",
	"wget",
]
