[packages]
linux = [
	"alacritty",
	"asciinema",
	"bash-completion",
	"bat",
	"bc",
	"blesh-git",
	"btop",
	"curl",
	"fastfetch",
	"firefox",
	"fzf",
	"git",
	"github-cli",
	"go",
	"gomatrix-git",
	"keychain",
	"less",
	"lftp",
	"libreoffice-still",
	"man-db",
	"neovim",
	"noto-fonts-cjk",
	"nvm",
	"obsidian",
	"pandoc",
	"pass",
	"ripgrep",
	"rsync",
	"starship",
	"tmux",
	"tree",
	"ttf-jetbrains-mono-nerd",
	"unzip",
	"vim",
	"wget",
]

[packages.darwin]
casks = ["alacritty", "google-chrome", "obsidian", "slack", "zoom"]
brews = [
	"asciinema",
	"bash",
	"bash-completion",
	"bat",
	"bc",
	"btop",
	"curl",
	"fastfetch",
	"fzf",
	"gcc",
	"git",
	"go",
	"keychain",
	"less",
	"lftp",
	"neovim",
	"nvm",
	"pandoc",
	"ripgrep",
	"starship",
	"tmux",
	"tree",
	"unzip",
	"vim",
	"wget",
]
