[packages]
linux = [
	"1password",
	"1password-cli",
	"dasel",
	"ghostty",
	"git",
	"greetd",
	"gtk-engine-murrine",
	"nwg-shell",
	"tokyonight-gtk-theme-git",
]
cachyos = ["cacyos-gaming-meta", "cachyos-gaming-applications"]
