[packages]
linux = [
  "1password",
  "1password-cli",
  "bash-completion",
  "bat",
  "blesh-git",
  "chezmoi",
  "dasel",
  "discord",
  "dos2unix",
  "fastfetch",
  "fzf",
  "ghostty",
  "git",
  "github-cli",
  "go",
  "greetd",
  "gtk-engine-murrine",
  "kanata",
  "neovim",
  "nerd-fonts-inter",
  "nvm",
  "nwg-shell",
  "obsidian",
  "pipewire",
  "protonplus",
  "protonup-qt",
  "protonutils",
  "ripgrep",
  "rofi-wayland",
  "spotify",
  "starship",
  "tmux",
  "tokyonight-gtk-theme-git",
  "tree",
  "ttf-jetbrains-mono-nerd",
  "ufw",
  "ufw-docker",
  "vim",
  "wireplumber",
  "xdg-desktop-portal-hyprland",
  "zen-browser",
]
cachyos = [
  "cachyos-gaming-meta",
  "cachyos-gaming-applications",
  "cachyos-gaming-meta",
  "cachyos-plymouth-bootanimation",
  "grub-btrfs-support",
]
