[packages]
linux = [
	"1password-cli",
	"1password",
	"bash-completion",
	"bat",
	"blesh-git",
	"chezmoi",
	"dasel",
	"discord_arch_electron",
	"dos2unix",
	"fastfetch",
	"fzf",
	"ghostty",
	"git",
	"github-cli",
	"go",
	"greetd",
	"gtk-engine-murrine",
	"kanata",
	"neovim",
	"nvm",
	"nwg-shell",
	"obsidian",
	"ripgrep",
	"starship",
	"tmux",
	"tokyonight-gtk-theme-git",
	"tree",
	"ttf-jetbrains-mono-nerd",
	"vim",
	"zen-browser"
]
cachyos = ["cachyos-gaming-meta", "cachyos-gaming-applications"]
