[packages]
linux = [
	"1password",
	"1password-cli",
	"alacritty",
	"asciinema",
	"bash-completion",
	"bat",
	"bc",
	"blesh-git",
	"btop",
	"curl",
	"fastfetch",
	"firefox",
	"fzf",
	"gamemode",
	"git",
	"github-cli",
	"go",
	"gomatrix-git",
	"google-chrome",
	"keychain",
	"less",
	"lftp",
	"lib32-gamemode",
	"libreoffice-still",
	"lutris",
	"man-db",
	"neovim",
	"noto-fonts-cjk",
	"nvm",
	"obsidian",
	"pandoc",
	"pass",
	"ripgrep",
	"rsync",
	"starship",
	"tmux",
	"tree",
	"ttf-jetbrains-mono-nerd",
	"unzip",
	"vim",
	"wget",
]
