[packages]
personal = [
	"apparmor",
	"arch-install-scripts",
	"ark",
	"base",
	"base-devel",
	"bash-completion",
	"bc",
	"bluez-utils",
	"btop",
	"btrfs-progs",
	"cups",
	"debtap",
	"dkms",
	"dolphin",
	"edk2-ovmf",
	"efibootmgr",
	"egl-wayland",
	"epson-inkjet-printer-201215w",
	"fd",
	"flatpak",
	"ghostscript",
	"grub",
	"grub-btrfs",
	"gst-plugin-pipewire",
	"guestfs-tools",
	"inotify-tools",
	"intel-ucode",
	"iwd",
	"kate",
	"kdeconnect",
	"layer-shell-qt5",
	"less",
	"libosinfo",
	"libpulse",
	"libreoffice-still",
	"libvirt",
	"linux-firmware",
	"linux-headers",
	"ly",
	"man-db",
	"network-manager-applet",
	"networkmanager",
	"nfs-utils",
	"noto-fonts-cjk",
	"ntfs-3g",
	"nvidia-dkms",
	"nvidia-settings",
	"nvme-cli",
	"obsidian",
	"os-prober",
	"paru-git",
	"perl-image-exiftool",
	"pipewire",
	"pipewire-alsa",
	"pipewire-jack",
	"pipewire-pulse",
	"plasma-framework5",
	"plasma-meta",
	"plasma-workspace",
	"qemu-base",
	"qemu-full",
	"qemu-img",
	"qt5-quickcontrols",
	"smartmontools",
	"snapd",
	"spectacle",
	"starship",
	"steam",
	"steamcmd",
	"superfile",
	"swtpm",
	"sysstat",
	"thunderbird",
	"timeshift",
	"tuned",
	"unzip",
	"vesktop",
	"virt-install",
	"virt-manager",
	"virt-viewer",
	"wireless_tools",
	"wireplumber",
	"wl-clipboard",
	"xdg-utils",
	"xorg-xinit",
	"xorg-xrandr",
	"zram-generator",
	"pass",
]
